// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYCanwtiwo1qtuuhnXJCZekMVnrUdquQ0',
    appId: '1:479309714183:web:877416c964add58c1e2ba2',
    messagingSenderId: '479309714183',
    projectId: 'stockapp-a7786',
    authDomain: 'stockapp-a7786.firebaseapp.com',
    storageBucket: 'stockapp-a7786.appspot.com',
    measurementId: 'G-TT9HTVCB33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6NQQv18dKwBAau9gwUrp_z66uj5F-CCg',
    appId: '1:479309714183:android:cc518d2eff3776171e2ba2',
    messagingSenderId: '479309714183',
    projectId: 'stockapp-a7786',
    storageBucket: 'stockapp-a7786.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Np50Jvr66zbScR0xN01o10HE61DgTMU',
    appId: '1:479309714183:ios:b6e2918b78ecf7bd1e2ba2',
    messagingSenderId: '479309714183',
    projectId: 'stockapp-a7786',
    storageBucket: 'stockapp-a7786.appspot.com',
    iosClientId: '479309714183-lf0hnkek4td8s1pg8ehaabnn6u4ik3nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Np50Jvr66zbScR0xN01o10HE61DgTMU',
    appId: '1:479309714183:ios:b6e2918b78ecf7bd1e2ba2',
    messagingSenderId: '479309714183',
    projectId: 'stockapp-a7786',
    storageBucket: 'stockapp-a7786.appspot.com',
    iosClientId: '479309714183-lf0hnkek4td8s1pg8ehaabnn6u4ik3nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstProj',
  );
}
